language: node_js
node_js:
- node
env:
  global:
    secure: bhmD5yHhWkwmawTMQPB8Qf3cI1g8fg7QUoLFDbSK2mWr7rXrZsJHKNWls0L9KshG8zQJTzejnbBLD157f+3SKg1iez8Oq1kvD9LUwWDpkJijLrwxGYf37IhBSLG6nsZFVzyzAsrqi1n/nD3UXHy/PDPe+3JuzZHJLUQPzzXkWjZa2ITvQAYPlM1sqvCsJKoKJeZtjzkxwbo29CFoYx1z/4SJFF9VG2E+yjtIgJBFtqtR30TzghCCIPjCN0x7sBkGUUacehhTIbNNyXLkLdFP3oj0InERHInW+uHHCfZJKd2eVCBwCJHzl4NkcP1jZUqzyYhSjCy/AIUWLYaGiae/ozsdM3usSQ+BBya7T1Ap7pyKyIU1CGblvVkTckyqSpbqoE1lwvF6uFxu4K7rN/6WLwrUDB1KVrHgyZbBKDgzcV+s8Ynjj8ziD37NmCdnspeP0hfTUkQYe6M/xrHBwyM/+/xcAkd4UQXLdYOhLjB+m3qysDfQnBRnoTZs2VGtIIOaaLrmrr1QI+BhbaHjcLRGZ7aogWiepCjhQMb/Eu5ZNaEy7ou8Cpvub2tbK7pq1RHr8dZPBoHqvkzwLzfGRbLGMP3rKMeQz6OMPlLnUwwVS4OHJQrz/JZXYCkUKBK+lZt/NqKUlfLnNZ+T3RBYbvmuTsa7l9fVgDg75v5009qdRb8=
